config/routes.rb
Rails.application.routes.draw do

  resources :favorites
  resources :games
  resources :users
  resources :welcome

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :user, uniqueness: {scope: :game}
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :favorites
  has_many :users, through: :favorites

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :favorites
  has_many :games, through: :favorites



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :current_user

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end





end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def create
    game = Game.find(params[:game_id])
    user = User.find(params[:user_id])
    Favorite.create(game: game, user: user)
    flash[:notice] = "This game has been saved to your favorites"
    redirect_to game_path(game)
  end



end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all.shuffle
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by(name: params[:user][:name])
  user = user.try(:authenticate, params[:user][:password])
  return redirect_to(controller: 'sessions', action: 'new') unless user
  session[:user_id] = user.id
  @user = user
  redirect_to controller: 'welcome', action: 'home'
end

def destroy
  session.delete :user_id
  redirect_to '/'
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.create(user_params)
    return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to controller: 'welcome', action: 'home'
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_logged_in

  def home
    @favorites = Favorite.all.select {|f| f.user_id == @user.id }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<% @games.each do |game| %>
<ul>
  <li><%= link_to game.name, game %>, <%= game.release_year %></li>
</ul>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<h3><%= @game.genre %> game released in <%= @game.release_year %> by <%= @game.publisher %> for the <%= @game.platform.split(', ').to_sentence %></h3>
<br>
<%= image_tag(@game.image) %>


<%= button_to "Add to Favorites", favorites_path(game_id: @game.id, user_id: @user.id), method: :post %>
<%= flash[:notice] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favigames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' href='https://cdn.jsdelivr.net/gh/kognise/water.css@latest/dist/dark.min.css'>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/home.html.erb
<h1>Hi, <%= @user.name %></h1>

<% if @favorites.size > 0 %>
  <h2> Your Favorite Games: </h2>
  <p><% @favorites.each do |favorite|%></p>
    <li><%= link_to favorite.game.name, game_path(favorite.game.id) %></li>
  <% end %>
<% else %>
  <p>You don't have any favorites, yet.</p>
<% end %>
<br><br>
<%= link_to "See A List of The All-Time Greatest Games", games_path %>


<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>